on: 
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/archive_new_wells.yaml
      - R/archive_new_wells_csv.R
  schedule:
    - cron: "0 6 * * *"      
jobs:
  job1:
    runs-on: ubuntu-latest
    container: 
      image: morglum/monrstudio
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      BCGOV_GEOCODER_API: ${{ secrets.BCGOV_GEOCODER_API }}    
      BCGOV_DB: ${{ secrets.BCGOV_DB }}    
      BCGOV_HOST: ${{ secrets.BCGOV_HOST }}    
      BCGOV_PWD: ${{ secrets.BCGOV_PWD }}    
      BCGOV_USR: ${{ secrets.BCGOV_USR }}    
      
    steps:
      - uses: actions/checkout@v2
      - name: list files 
        run:  |
          ls * -lh
      - name: list files  data
        run:  |
          ls data/*                    
      - name: archive new wells
        run: |
          Rscript R/archive_new_wells_csv.R            
      - name: list files 
        run:  |
          ls * -lh          
      - name: list files  data
        run:  |
          ls data/*          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'data/wells.csv' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}          
